# Site Settings
lang: ko-KR
title: Combinatorial Algorithms Lab
# 연구 분야를 명시하여 검색 엔진에 잘 걸리도록 수정
tagline: Graph Theory & Combinatorial Algorithms Research Lab
email: junghoahn@inha.ac.kr
description: >
  인하대학교 조합적 알고리즘 연구실 홈페이지입니다. 
  그래프 이론 (Graph Theory)과 조합 알고리즘 (Combinatorial Algorithms)을 중점적으로 연구합니다.
baseurl: ""
url: "https://Combinatorial-Algorithms-Lab.github.io"
permalink: pretty

force_theme: light

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE.txt


# -----------------------
# Layout Defaults (기본 레이아웃)
# -----------------------
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
      show_sidebar: false # 페이지에서는 사이드바 숨김
      hero_height: is-custom
      hero_image: /assets/img/banner.png  
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Jungho Ahn"
      layout: post
      show_sidebar: true


# -----------------------
# Social & GitHub
# -----------------------
github_username: Combinatorial-Algorithms-Lab
github_repo: https://github.com/Combinatorial-Algorithms-Lab
  